"""add task image folder_path and task_folder_meta

Revision ID: 3f57854882f4
Revises: 81d00fb7554f
Create Date: 2026-03-23 13:16:50.038720
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f57854882f4'
down_revision: Union[str, None] = '81d00fb7554f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_folder_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'path')
    )
    op.create_index(op.f('ix_task_folder_meta_id'), 'task_folder_meta', ['id'], unique=False)
    op.add_column('task_images', sa.Column('folder_path', sa.String(length=1000), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_images', 'folder_path')
    op.drop_index(op.f('ix_task_folder_meta_id'), table_name='task_folder_meta')
    op.drop_table('task_folder_meta')
    # ### end Alembic commands ###
