"""add restored_from_id to task_snapshots

Revision ID: c3e5f287ddf6
Revises: d5e6f7a8b9c0
Create Date: 2026-03-28 13:11:01.563701
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c3e5f287ddf6'
down_revision: Union[str, None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_snapshots', sa.Column('restored_from_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_snapshots', 'task_snapshots', ['restored_from_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_snapshots', type_='foreignkey')
    op.drop_column('task_snapshots', 'restored_from_id')
    # ### end Alembic commands ###
