"""set ondelete SET NULL for annotations label_class_id

Revision ID: deaad1ba7e2d
Revises: c3e5f287ddf6
Create Date: 2026-03-28 13:58:24.699215
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'deaad1ba7e2d'
down_revision: Union[str, None] = 'c3e5f287ddf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('annotations_label_class_id_fkey'), 'annotations', type_='foreignkey')
    op.create_foreign_key(None, 'annotations', 'label_classes', ['label_class_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.create_foreign_key(op.f('annotations_label_class_id_fkey'), 'annotations', 'label_classes', ['label_class_id'], ['id'])
    # ### end Alembic commands ###
